#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header X-Served-By

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo service nginx start
