#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself
## when receiving a SIGQUIT or SIGTERM signal

sigquit_handler() {
    rm /var/run/myscript.pid
    exit
}
sigterm_handler() {
    echo "I hate the kill command"
    sigquit_handler
}
sigint_handler(){
    echo "Y U no love me?!"
}

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigterm_sigquit SIGQUIT

echo "$$" > /var/run/myscript.pid

while true; do
      echo "To infinity and beyond"
done
