#!/usr/bin/env bash
# Run Nginx as Nginx, and listen on port 8080

sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/user www-data/user nginx/g" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache
sudo -u nginx systemctl restart nginx.service
